import Head from "next/head";
// import Image from "next/image";
import styled from '@emotion/styled';
import { motion } from 'framer-motion';
import { Geist, Geist_Mono } from "next/font/google";
import styles from "@/styles/Home.module.css";
import ScrollEffect from '@/components/ScrollEffect'

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export default function Home() {
  return (
    <>
      <Head>
        <title>Am Sudhaus</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={`${styles.page} ${geistSans.variable} ${geistMono.variable}`}>
        <ScrollEffect />

        <Wrapper>
          <div className="businesscard">
            <span>
              <h1>Am Sudhaus</h1>
              <p>Fördergesellschaft für<br/>
              zeitgenössische Kunst gGmbH
              </p>
            </span>
            <span>
              <p>Am Sudhaus 3<br/>
                12053 Berlin
              </p>
              <a href="mailto:info@amsudhaus-berlin.de">info@amsudhaus-berlin.de</a>
            </span>
          </div>
        </Wrapper>
        
        <footer>
          <p>&copy; 2025</p>
        </footer>
      </div>    
    </>
  );
}

const Wrapper = styled.div`
  width: 100%;
  height: 100vh;
  display: flex;
  justify-content: center;
  align-items: center;
`