import Head from "next/head";
// import Image from "next/image";
import styled from "@emotion/styled";
import { motion } from "motion/react";
import { Geist, Geist_Mono } from "next/font/google";
import styles from "@/styles/Home.module.css";
import ScrollEffect from "@/components/ScrollEffect"
import Cursor from "@/components/Cursor"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const variants = {
  hidden: { clipPath: 'polygon(0 100%, 100% 100%, 100% 100%, 0% 100%)' },
  show: {
    clipPath: 'polygon(0% 0%, 100% 0%, 100% 100%, 0% 100%)',
    transition: { ease: [0.25, 0.1, 0.25, 1], staggerChildren: 0.05, delay: 0.5, duration: .9 }
  },
};

const c1 = {
  hidden: { opacity: 0, y: 10 },
  show: {
    opacity: 1,
    y: 0,
    transition: { delay: 1.2, duration: 1 }
  },
};

const c2 = {
  hidden: { opacity: 0, y: 20 },
  show: {
    opacity: 1,
    y: 0,
    transition: { delay: .9, duration: 1 }
  },
};

export default function Home() {
  return (
    <>
      <Head>
        <title>Am Sudhaus</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={`${styles.page} ${geistSans.variable} ${geistMono.variable}`}>
        {/* <Cursor/> */}

        <ScrollEffect />

        <Wrapper>
          <motion.div
            variants={variants} 
            initial="hidden"
            animate="show"
            className="businesscard">
            <motion.span initial="hidden" animate="show" variants={c1}>
              <h1>Am Sudhaus</h1>
              <p>Fördergesellschaft für<br/>
              zeitgenössische Kunst gGmbH
              </p>
            </motion.span>
            <motion.span initial="hidden" animate="show" variants={c2}>
              <p>Am Sudhaus 3<br/>
                12053 Berlin
              </p>
              <a href="mailto:info@amsudhaus-berlin.de">info@amsudhaus-berlin.de</a>
            </motion.span>
          </motion.div>
        </Wrapper>
        
        <footer>
          <p>&copy; 2025</p>
        </footer>
      </div>    
    </>
  );
}

const Wrapper = styled.div`
  width: 100%;
  height: 100vh;
  display: flex;
  justify-content: center;
  align-items: center;
`